services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    mem_limit: 512m   # or 768m â€” Mongo starts fine with this
    mem_reservation: 256m
  app:
    build: .
    container_name: ruby-app
    ports:
      - "4567:4567"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo